### ISSUE TITLE
Social Integration

### ISSUE THREAD

**Issue by kirpeep** [kirpeep/Kirpeep#8]
This includes sharing listing and profiles over social networks

**Comment by kyleondata** [comment]
Once completed on your end assign to me so I can add social media links.

**Comment by kyleondata** [comment]
do we want to launch with just sharing on FB for now?

**Comment by kirpeep** [comment]
is there a way to do that for twitter as well?

**Comment by kyleondata** [comment]
Ya. But have to also get an app setup for as well

**Comment by kyleondata** [comment]
So I looked into this further and it looks like the only app we have to "create" is a facebook app.  Twitter and pintrest do not require it for a share link.  So I can add the the twitter and pintrest easily.  

However, I will need Steven to look into getting the Facebook app created.  I will need the public app key in order to get facebook sharing working.

**Comment by kyleondata** [comment]
Twitter and pint rest works getting an error in the FB sharing. Will take a look at it

**Comment by kirpeep** [comment]
any update on FB?

**Comment by kyleondata** [comment]
We need to test it, but I think the settings in the app on facebook are off.  Not sure but I think it needs to be pointed to test.kirpeep.com not www.kirpeep.com  or kirpeep.com.  Also we may have to turn on some kind of sandbox setting.

Can someone look into the settings please

**Comment by kyleondata** [comment]
facebook works now!
